apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: httpbin
spec:
  components:
  - name: httpbin
    type: webservice
    properties:
      image: kennethreitz/httpbin:latest
      port: 80
    traits:
    - type: cpuscaler
      properties:
        min: 2
        max: 5
        cpuPercent: 80
    - type: gateway
      properties:
        class: traefik
        classInSpec: true
        domain: httpbin.127.0.0.1.nip.io
        http:
          "/": 8080